In [3]:
import numpy as np

In [ ]:
# creating an crray
arr = np.array([10,20,30,40,50])
print(arr, type(arr))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [8]:
# array is the collection of homogenueous element
print(arr.dtype)

int64


In [25]:
arr2 = np.array([10.0,20,30,40,50])
print(arr2, type(arr2))

[10. 20. 30. 40. 50.] <class 'numpy.ndarray'>


In [18]:
# 2D array
arr2d = np.array([10,20,30,40,50,60]).reshape(2,3)
print(arr2d)

[[10 20 30]
 [40 50 60]]


In [ ]:
# size of the array
print(arr.size)
print(arr2d.size)

5
6


In [ ]:
# diamentions of an array
print(arr2.ndim)  #1D
print(arr2d.ndim) #2D

1
2


In [ ]:
# number of bytes taken by the array to store all the element in the array
print(arr.nbytes)
print(arr2d.nbytes)

40
48


In [43]:
# convert to the float
arr = np.array((10,20,30,40,50.60))
print(arr)
print(arr.dtype)

[10.  20.  30.  40.  50.6]
float64


In [42]:
# convert to the string
arr3 = np.array([10,20,30,40,30.40, 'manish'])
print(arr3)
print(arr3.dtype)

['10' '20' '30' '40' '30.4' 'manish']
<U32


In [41]:
# convert to the object (manually need to give if want to convert in object)
arr4 = np.array([10,20,30,40,30.40,[20,30], 'manish'], dtype='object')
print(arr4)
print(arr4.dtype)

[10 20 30 40 30.4 list([20, 30]) 'manish']
object


### Creating 2D array

In [51]:
# creating 2D array
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr, type(arr))
print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
int64


In [ ]:
arr.shape

2

### functions to create an array
1. arange - start,end,step
2. linspace - start,stop,number of element

In [62]:
# 1. arange - can take a fractional value as step whereas range can take only integer value
arr1 = np.arange(10,21)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [63]:
arr1 = np.arange(10,21,1.5)
arr1

array([10. , 11.5, 13. , 14.5, 16. , 17.5, 19. , 20.5])

In [69]:
# 2. linspace(start,stop,no_of_element)
arr2 = np.linspace(1,100,100)
arr2

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [ ]:
# creating an array with all zeros elements of shape (6,)
arr3 = np.zeros((6,))
arr3

array([0., 0., 0., 0., 0., 0.])

In [80]:
# creating an array with all zeros elements of shape (4,3,)
arr3 = np.zeros((4,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
# creating an array with all 1 elements of shape (6,)
arr3 = np.ones((6,))
arr3

array([1., 1., 1., 1., 1., 1.])

In [82]:
# creating an array with all 1 elements of shape (4,3,)
arr3 = np.ones((4,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [88]:
# identity array - diaginal from top left to right all are 1
# rest all element are zero
# no of rows and cols will always be same

arr4 = np.eye(4,4)
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
# create erray with random values (start,end,no_of_element)
arr5 = np.random.randint(10,50,50)
arr5


array([36, 21, 41, 47, 21, 26, 45, 32, 18, 29, 44, 45, 42, 22, 34, 32, 12,
       29, 48, 37, 41, 25, 41, 14, 37, 38, 35, 18, 33, 19, 45, 33, 11, 42,
       19, 40, 23, 48, 28, 17, 17, 15, 10, 38, 20, 17, 48, 15, 40, 29],
      dtype=int32)

In [98]:
arr5.shape

(50,)

## Reshaping of Array

In [3]:
shape_arr = np.random.randint(10,100,50)
shape_arr

array([81, 80, 73, 87, 64, 57, 53, 38, 63, 33, 70, 87, 61, 70, 80, 21, 27,
       97, 40, 73, 16, 46, 72, 63, 91, 18, 66, 14, 94, 33, 54, 62, 56, 45,
       16, 82, 10, 83, 71, 49, 61, 11, 97, 58, 57, 52, 51, 13, 92, 10],
      dtype=int32)

In [15]:
arr_shaped = shape_arr.reshape(10,5)
arr_shaped

array([[81, 80, 73, 87, 64],
       [57, 53, 38, 63, 33],
       [70, 87, 61, 70, 80],
       [21, 27, 97, 40, 73],
       [16, 46, 72, 63, 91],
       [18, 66, 14, 94, 33],
       [54, 62, 56, 45, 16],
       [82, 10, 83, 71, 49],
       [61, 11, 97, 58, 57],
       [52, 51, 13, 92, 10]], dtype=int32)

Multiplication of shape should be equal to the number of element of original then only reshape function will work

In [20]:
arr_shaped.reshape(1,50)

array([[81, 80, 73, 87, 64, 57, 53, 38, 63, 33, 70, 87, 61, 70, 80, 21,
        27, 97, 40, 73, 16, 46, 72, 63, 91, 18, 66, 14, 94, 33, 54, 62,
        56, 45, 16, 82, 10, 83, 71, 49, 61, 11, 97, 58, 57, 52, 51, 13,
        92, 10]], dtype=int32)

If we are trying to reshape with -ve value of diamentions then it will automatically create the array with poosible diamention          
note :- will check first what we given x(row) or y(column) then it will create

In [39]:
# Rehaping using shape attribute
# shape atribute make changes in existing array
shape_arr2 = shape_arr
shape_arr2.shape = (5,10,-5)
shape_arr2

array([[[81],
        [80],
        [73],
        [87],
        [64],
        [57],
        [53],
        [38],
        [63],
        [33]],

       [[70],
        [87],
        [61],
        [70],
        [80],
        [21],
        [27],
        [97],
        [40],
        [73]],

       [[16],
        [46],
        [72],
        [63],
        [91],
        [18],
        [66],
        [14],
        [94],
        [33]],

       [[54],
        [62],
        [56],
        [45],
        [16],
        [82],
        [10],
        [83],
        [71],
        [49]],

       [[61],
        [11],
        [97],
        [58],
        [57],
        [52],
        [51],
        [13],
        [92],
        [10]]], dtype=int32)

In [41]:
# flatteing of an array - converting higher diamension array into single diam
shape_arr2.ravel()

array([81, 80, 73, 87, 64, 57, 53, 38, 63, 33, 70, 87, 61, 70, 80, 21, 27,
       97, 40, 73, 16, 46, 72, 63, 91, 18, 66, 14, 94, 33, 54, 62, 56, 45,
       16, 82, 10, 83, 71, 49, 61, 11, 97, 58, 57, 52, 51, 13, 92, 10],
      dtype=int32)

In [ ]:
# transpose of matrix 
shape_arr2.T

array([[[81, 70, 16, 54, 61],
        [80, 87, 46, 62, 11],
        [73, 61, 72, 56, 97],
        [87, 70, 63, 45, 58],
        [64, 80, 91, 16, 57],
        [57, 21, 18, 82, 52],
        [53, 27, 66, 10, 51],
        [38, 97, 14, 83, 13],
        [63, 40, 94, 71, 92],
        [33, 73, 33, 49, 10]]], dtype=int32)

### Arithmatic operations on array  


In [59]:
arr6 = np.random.randint(10,50,10)
arr7 = np.random.randint(10,50,10)
print(arr6)
print(arr7)


[27 41 49 27 40 31 46 38 28 19]
[45 36 28 32 21 15 48 31 43 39]


In [62]:
print(arr6 + 5)
print(arr6 - 5)
print(arr6 * 5)
print(arr6 ** 5)
print(arr6 / 5)

[32 46 54 32 45 36 51 43 33 24]
[22 36 44 22 35 26 41 33 23 14]
[135 205 245 135 200 155 230 190 140  95]
[ 14348907 115856201 282475249  14348907 102400000  28629151 205962976
  79235168  17210368   2476099]
[5.4 8.2 9.8 5.4 8.  6.2 9.2 7.6 5.6 3.8]


### conditional operations


In [64]:
print(arr6 > arr7)
print(arr6 < arr7)
print(arr6 <= arr7)
print(arr6 >= arr7)
print(arr6 == arr7)

[False  True  True False  True  True False  True False False]
[ True False False  True False False  True False  True  True]
[ True False False  True False False  True False  True  True]
[False  True  True False  True  True False  True False False]
[False False False False False False False False False False]


uniary operation on array - max,min,sum

In [71]:
print(np.max(arr7))
print(np.min(arr7))
print(np.sum(arr7))
print(np.min(arr7))


48
15
338
15


In [11]:
fruit = np.array([['banana','payaya','apple'],
                  ['jack','guava','plum'],
                  ['apple','blue berry','black berry']])

In [75]:
row_index = [0,1,1,2]
col_index = [1,1,0,2]
fruit[row_index,col_index] = 'potato'
fruit

array([['banana', 'potato', 'apple'],
       ['potato', 'potato', 'plum'],
       ['apple', 'blue berry', 'potato']], dtype='<U11')

In [6]:
arr8 = np.random.randint(10,30,30).reshape(5,6)
arr8

array([[12, 17, 24, 18, 17, 26],
       [18, 18, 14, 12, 14, 14],
       [13, 18, 15, 10, 20, 18],
       [26, 29, 18, 26, 10, 13],
       [11, 20, 13, 22, 15, 29]], dtype=int32)

In [78]:
#return the bool value 
arr8 < 15

array([[False, False, False, False, False, False],
       [False, False, False,  True,  True, False],
       [False, False, False, False,  True,  True],
       [False, False,  True, False,  True, False],
       [ True, False, False, False, False, False]])

In [81]:
# Accesing the all the element which is greate then 50 
arr8[arr8 > 15]

array([22, 28, 17, 29, 20, 20, 17, 18, 24, 24, 18, 24, 16, 25, 26, 22, 29,
       17, 22, 21, 19, 20], dtype=int32)

In [84]:
# count total number of element greater then 15
np.sum(arr8 > 15)

np.int64(22)

In [7]:
for ele in np.nditer(arr8, order='F'):
    
    print(ele)

12
18
13
26
11
17
18
18
29
20
24
14
15
18
13
18
12
10
26
22
17
14
20
10
15
26
14
18
13
29


spliting the array using split function

<!-- split function -->

In [ ]:

arr9 = np.random.randint(10,30,30)
np.split(arr9,6)

[array([22, 27, 17, 12, 19], dtype=int32),
 array([10, 15, 20, 19, 15], dtype=int32),
 array([12, 18, 14, 11, 27], dtype=int32),
 array([14, 10, 27, 28, 12], dtype=int32),
 array([29, 14, 15, 23, 17], dtype=int32),
 array([26, 27, 12, 22, 11], dtype=int32)]

In [29]:
# 2D spliting
arr10 = np.random.randint(10,30,30).reshape(5,6)
np.split(arr10,2) 

ValueError: array split does not result in an equal division

here we can not divide on axis = 0 because it is not equality divided

In [32]:
# for divding 
np.split(arr10,2,axis=1)

[array([[20, 28, 29],
        [22, 14, 23],
        [28, 16, 12],
        [15, 11, 20],
        [12, 20, 11]], dtype=int32),
 array([[25, 23, 14],
        [28, 21, 25],
        [13, 28, 14],
        [27, 26, 16],
        [18, 24, 21]], dtype=int32)]

so here it was divided equally so it's splited into two part

## Concadination Of Array

In [35]:
#1. if all array are of same shape and size
#2. along the column- if no of rows in all the arrays are same
#3. along the rows -  if no of col in all the arrays are same

arr1 = np.random.randint(10,50,5)
arr1

array([15, 22, 48, 41, 12], dtype=int32)

In [36]:
arr2 = np.random.randint(10,50,5)
arr2

array([28, 23, 44, 39, 10], dtype=int32)

In [38]:
np.concatenate((arr1,arr2))

array([15, 22, 48, 41, 12, 28, 23, 44, 39, 10], dtype=int32)

In [40]:
#2D
arr1 = np.random.randint(10,50,15).reshape(5,3)
arr1

array([[10, 24, 29],
       [27, 20, 48],
       [14, 31, 25],
       [27, 33, 43],
       [24, 44, 26]], dtype=int32)

In [42]:
#2D
arr2 = np.random.randint(10,50,6).reshape(2,3)
arr2

array([[17, 44, 13],
       [10, 16, 28]], dtype=int32)

In [45]:
np.concatenate((arr1,arr2), axis = 0)

array([[10, 24, 29],
       [27, 20, 48],
       [14, 31, 25],
       [27, 33, 43],
       [24, 44, 26],
       [17, 44, 13],
       [10, 16, 28]], dtype=int32)

In [47]:
np.concatenate((arr1,arr2), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 2