In [4]:
import numpy as np

In [ ]:
# creating an crray
arr = np.array([10,20,30,40,50])
print(arr, type(arr))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [8]:
# array is the collection of homogenueous element
print(arr.dtype)

int64


In [25]:
arr2 = np.array([10.0,20,30,40,50])
print(arr2, type(arr2))

[10. 20. 30. 40. 50.] <class 'numpy.ndarray'>


In [18]:
# 2D array
arr2d = np.array([10,20,30,40,50,60]).reshape(2,3)
print(arr2d)

[[10 20 30]
 [40 50 60]]


In [ ]:
# size of the array
print(arr.size)
print(arr2d.size)

5
6


In [ ]:
# diamentions of an array
print(arr2.ndim)  #1D
print(arr2d.ndim) #2D

1
2


In [ ]:
# number of bytes taken by the array to store all the element in the array
print(arr.nbytes)
print(arr2d.nbytes)

40
48


In [43]:
# convert to the float
arr = np.array((10,20,30,40,50.60))
print(arr)
print(arr.dtype)

[10.  20.  30.  40.  50.6]
float64


In [42]:
# convert to the string
arr3 = np.array([10,20,30,40,30.40, 'manish'])
print(arr3)
print(arr3.dtype)

['10' '20' '30' '40' '30.4' 'manish']
<U32


In [41]:
# convert to the object (manually need to give if want to convert in object)
arr4 = np.array([10,20,30,40,30.40,[20,30], 'manish'], dtype='object')
print(arr4)
print(arr4.dtype)

[10 20 30 40 30.4 list([20, 30]) 'manish']
object


### Creating 2D array

In [51]:
# creating 2D array
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr, type(arr))
print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
int64


In [ ]:
arr.shape

2

### functions to create an array
1. arange - start,end,step
2. linspace - start,stop,number of element

In [62]:
# 1. arange - can take a fractional value as step whereas range can take only integer value
arr1 = np.arange(10,21)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [63]:
arr1 = np.arange(10,21,1.5)
arr1

array([10. , 11.5, 13. , 14.5, 16. , 17.5, 19. , 20.5])

In [69]:
# 2. linspace(start,stop,no_of_element)
arr2 = np.linspace(1,100,100)
arr2

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [ ]:
# creating an array with all zeros elements of shape (6,)
arr3 = np.zeros((6,))
arr3

array([0., 0., 0., 0., 0., 0.])

In [80]:
# creating an array with all zeros elements of shape (4,3,)
arr3 = np.zeros((4,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
# creating an array with all 1 elements of shape (6,)
arr3 = np.ones((6,))
arr3

array([1., 1., 1., 1., 1., 1.])

In [82]:
# creating an array with all 1 elements of shape (4,3,)
arr3 = np.ones((4,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])